Repository elastic/terraform-provider-elasticstack, pull requests merged in 2022-01, with the labels that each got.

#36 add insecure option to disable TLS validation
  docs/data-sources/elasticsearch_security_user.md
  docs/data-sources/elasticsearch_snapshot_repository.md
  docs/index.md
  docs/resources/elasticsearch_cluster_settings.md
  docs/resources/elasticsearch_index_lifecycle.md
  docs/resources/elasticsearch_index_template.md
  docs/resources/elasticsearch_security_role.md
  docs/resources/elasticsearch_security_user.md
  docs/resources/elasticsearch_snapshot_lifecycle.md
  docs/resources/elasticsearch_snapshot_repository.md
  internal/clients/api_client.go
  internal/provider/provider.go
  internal/utils/utils.go
Labels: enhancement

#35 add "ca_file" option to the elasticstack provider
  docs/data-sources/elasticsearch_security_user.md
  docs/data-sources/elasticsearch_snapshot_repository.md
  docs/index.md
  docs/resources/elasticsearch_cluster_settings.md
  docs/resources/elasticsearch_index_lifecycle.md
  docs/resources/elasticsearch_index_template.md
  docs/resources/elasticsearch_security_role.md
  docs/resources/elasticsearch_security_user.md
  docs/resources/elasticsearch_snapshot_lifecycle.md
  docs/resources/elasticsearch_snapshot_repository.md
  internal/clients/api_client.go
  internal/provider/provider.go
  internal/utils/utils.go
Labels: enhancement

#38 Add Index resource
  docs/resources/elasticsearch_index.md
  docs/resources/elasticsearch_index_template.md
  examples/resources/elasticstack_elasticsearch_index/import.sh
  examples/resources/elasticstack_elasticsearch_index/resource.tf
  examples/resources/elasticstack_elasticsearch_index_template/resource.tf
  internal/clients/api_client.go
  internal/elasticsearch/cluster/settings.go
  internal/elasticsearch/index/commons.go
  internal/elasticsearch/index/index.go
  internal/elasticsearch/index/index_test.go
  internal/elasticsearch/index/template.go
  internal/elasticsearch/index/template_test.go
  internal/models/models.go
  internal/provider/provider.go
  internal/utils/diffs.go
  internal/utils/utils_test.go
  templates/resources/elasticsearch_index.md.tmpl
Labels: enhancement

#40 Identify the missing/deleted resources in ES cluster
  internal/clients/api_client.go
  internal/clients/cluster.go
  internal/clients/index.go
  internal/clients/security.go
  internal/elasticsearch/cluster/slm.go
  internal/elasticsearch/cluster/snapshot_repository.go
  internal/elasticsearch/index/ilm.go
  internal/elasticsearch/index/template.go
  internal/elasticsearch/security/role.go
  internal/elasticsearch/security/user.go
Labels: bug

#41 Add CHANGELOG.md file
  CHANGELOG.md
  Makefile
Labels: documentation

#43 Update versions and changelog after release
  CHANGELOG.md
  Makefile
  README.md
  docs/guides/elasticstack-and-cloud.md
  examples/cloud/deployment.tf
  examples/cloud/provider.tf
Labels: documentation

#44 Added title in the cloud guide
  docs/guides/elasticstack-and-cloud.md
  templates/guides/elasticstack-and-cloud.md.tmpl
Labels: documentation

#45 Add data stream resource
  CHANGELOG.md
  docs/resources/elasticsearch_data_stream.md
  examples/resources/elasticstack_elasticsearch_data_stream/import.sh
  examples/resources/elasticstack_elasticsearch_data_stream/resource.tf
  internal/clients/index.go
  internal/elasticsearch/index/data_stream.go
  internal/elasticsearch/index/data_stream_test.go
  internal/models/models.go
  internal/provider/provider.go
  templates/resources/elasticsearch_data_stream.md.tmpl
Labels: enhancement, Elasticsearch
