Repository elastic/terraform-provider-elasticstack, pull requests merged in 2023-11, with the labels that each got.

#467 Added cluster info data source
  CHANGELOG.md
  docs/data-sources/elasticsearch_info.md
  examples/data-sources/elasticstack_elasticsearch_info/data-source.tf
  internal/clients/elasticsearch/cluster.go
  internal/elasticsearch/cluster/cluster_info_data_source.go
  internal/elasticsearch/cluster/cluster_info_data_source_test.go
  provider/provider.go
  templates/data-sources/elasticsearch_info.md.tmpl
Labels: documentation, enhancement, Elasticsearch, datasource

#476 Rename fleet package objects to use integration terminology
  CHANGELOG.md
  docs/data-sources/fleet_integration.md
  docs/resources/fleet_integration.md
  docs/resources/fleet_integration_policy.md
  examples/data-sources/elasticstack_fleet_integration/data-source.tf
  examples/resources/elasticstack_fleet_integration/resource.tf
  examples/resources/elasticstack_fleet_integration_policy/import.sh
  examples/resources/elasticstack_fleet_integration_policy/resource.tf
  examples/resources/elasticstack_fleet_package_policy/import.sh
  internal/fleet/integration_data_source.go
  internal/fleet/integration_data_source_test.go
  internal/fleet/integration_policy_resource.go
  internal/fleet/integration_policy_resource_test.go
  internal/fleet/integration_resource.go
  internal/fleet/integration_resource_test.go
  internal/fleet/package_policy_resource_test.go
  provider/provider.go
  templates/data-sources/fleet_integration.md.tmpl
  templates/resources/fleet_integration.md.tmpl
  templates/resources/fleet_integration_policy.md.tmpl
Labels: enhancement

#493 Make input optional for Fleet integration policies
  CHANGELOG.md
  docs/resources/fleet_integration_policy.md
  internal/fleet/integration_policy_resource.go
Labels: bug

#494 Sort Fleet integration policy inputs to ensure consistency
  CHANGELOG.md
  internal/fleet/integration_policy_resource.go
  internal/fleet/shared_test.go
Labels: bug
